services:
  - type: web
    name: laravel-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://uber-aviones.onrender.com
      - key: DB_SSLMODE
        value: require
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: red-aviation
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: red-aviation-images
      - key: AWS_URL
        value: https://red-aviation-images.s3.us-east-1.amazonaws.com
      - key: AWS_ENDPOINT
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false
      - key: AWS_EC2_METADATA_DISABLED
        value: true
