<?php

use App\Http\Controladores\AdministradorControlador;
use App\Http\Controladores\AdminAircraftChecklistController;
use App\Http\Controladores\AeronaveControlador;
use App\Http\Controladores\RedAviation\AdminControlador as RedAviationAdminControlador;
use App\Http\Controladores\RedAviation\FlightMembershipAdminControlador;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->middleware(['auth.token', 'role:admin'])->group(function () {
    Route::get('/dashboard-marketplace', [RedAviationAdminControlador::class, 'dashboard']);
    Route::get('/usuarios', [AdministradorControlador::class, 'users']);
    Route::get('/users', [AdministradorControlador::class, 'users']);
    Route::get('/usuarios/{user}', [AdministradorControlador::class, 'showUsuario']);
    Route::get('/users/{user}', [AdministradorControlador::class, 'showUsuario']);
    Route::put('/usuarios/{user}', [AdministradorControlador::class, 'updateUsuario']);
    Route::put('/users/{user}', [AdministradorControlador::class, 'updateUsuario']);
    Route::post('/usuarios/{user}/bloquear', [AdministradorControlador::class, 'blockUsuario']);
    Route::post('/users/{user}/block', [AdministradorControlador::class, 'blockUsuario']);
    Route::post('/usuarios/{user}/activar', [AdministradorControlador::class, 'activateUsuario']);
    Route::post('/users/{user}/activate', [AdministradorControlador::class, 'activateUsuario']);

    Route::get('/clientes', [AdministradorControlador::class, 'clients']);
    Route::get('/providers', [AdministradorControlador::class, 'providers']);
    Route::get('/proveedores', [AdministradorControlador::class, 'providers']);
    Route::get('/providers/{provider}', [AdministradorControlador::class, 'showProveedor']);
    Route::get('/providers/{provider}/detail', [AdministradorControlador::class, 'showProveedor']);
    Route::get('/providers/{provider}/activity', [AdministradorControlador::class, 'providerActivity']);
    Route::get('/providers/{provider}/documents', [AdministradorControlador::class, 'providerDocuments']);
    Route::get('/providers/{provider}/documents/{document}/download', [AdministradorControlador::class, 'downloadProviderDocument']);
    Route::patch('/providers/{provider}/documents/{document}', [AdministradorControlador::class, 'updateProviderDocument']);
    Route::post('/providers/{provider}/documents/{document}/approved', [AdministradorControlador::class, 'approveProviderDocument']);
    Route::post('/providers/{provider}/documents/{document}/rejected', [AdministradorControlador::class, 'rejectProviderDocument']);
    Route::post('/providers/{provider}/requirements/{requirement}/approve', [AdministradorControlador::class, 'approveProviderRequirement']);
    Route::post('/providers/{provider}/requirements/{requirement}/reject', [AdministradorControlador::class, 'rejectProviderRequirement']);
    Route::get('/proveedores/{provider}', [AdministradorControlador::class, 'showProveedor']);
    Route::get('/proveedores/{provider}/detalle', [AdministradorControlador::class, 'showProveedor']);
    Route::get('/proveedores/{provider}/actividad', [AdministradorControlador::class, 'providerActivity']);
    Route::get('/proveedores/{provider}/documentos', [AdministradorControlador::class, 'providerDocuments']);
    Route::get('/proveedores/{provider}/documentos/{document}/descargar', [AdministradorControlador::class, 'downloadProviderDocument']);
    Route::patch('/proveedores/{provider}/documentos/{document}', [AdministradorControlador::class, 'updateProviderDocument']);
    Route::post('/proveedores/{provider}/documentos/{document}/approved', [AdministradorControlador::class, 'approveProviderDocument']);
    Route::post('/proveedores/{provider}/documentos/{document}/rejected', [AdministradorControlador::class, 'rejectProviderDocument']);
    Route::post('/proveedores/{provider}/requisitos/{requirement}/aprobar', [AdministradorControlador::class, 'approveProviderRequirement']);
    Route::post('/proveedores/{provider}/requisitos/{requirement}/rechazar', [AdministradorControlador::class, 'rejectProviderRequirement']);
    Route::post('/providers/{provider}/approve', [AdministradorControlador::class, 'approveProveedor']);
    Route::post('/providers/{provider}/validate', [AdministradorControlador::class, 'validateProveedor']);
    Route::post('/providers/{provider}/request-changes', [AdministradorControlador::class, 'requestProviderChanges']);
    Route::post('/providers/{provider}/reject', [AdministradorControlador::class, 'rejectProviderValidation']);
    Route::post('/proveedores/{provider}/validar', [AdministradorControlador::class, 'validateProveedor']);
    Route::post('/proveedores/{provider}/solicitar-cambios', [AdministradorControlador::class, 'requestProviderChanges']);
    Route::post('/proveedores/{provider}/cancelar-validacion', [AdministradorControlador::class, 'rejectProviderValidation']);
    Route::post('/proveedores/{provider}/aprobar', [AdministradorControlador::class, 'approveProveedor']);
    Route::post('/proveedores/{provider}/rechazar', [AdministradorControlador::class, 'rejectProveedor']);
    Route::post('/proveedores/{provider}/suspender', [AdministradorControlador::class, 'suspendProveedor']);
    Route::get('/company-documents/{document}/download', [AdministradorControlador::class, 'downloadCompanyDocumentByDocument']);
    Route::post('/company-documents/{document}/approved', [AdministradorControlador::class, 'approveCompanyDocumentByDocument']);
    Route::post('/company-documents/{document}/rejected', [AdministradorControlador::class, 'rejectCompanyDocumentByDocument']);
    Route::get('/sobrecargos', [RedAviationAdminControlador::class, 'sobrecargos']);
    Route::put('/sobrecargos/{user}', [RedAviationAdminControlador::class, 'updateSobrecargo']);
    Route::get('/crew', [RedAviationAdminControlador::class, 'sobrecargos']);
    Route::put('/crew/{user}', [RedAviationAdminControlador::class, 'updateSobrecargo']);

    Route::get('/aeronaves', [AdministradorControlador::class, 'aircraft']);
    Route::get('/aeronaves/{aircraft}/checklist', [AdminAircraftChecklistController::class, 'show']);
    Route::put('/aeronaves/{aircraft}/checklist', [AdminAircraftChecklistController::class, 'update']);
    Route::get('/aircraft-calendar', [RedAviationAdminControlador::class, 'aircraftCalendar']);
    Route::get('/operations/dashboard', [RedAviationAdminControlador::class, 'operationsDashboard']);
    Route::get('/operations/history', [RedAviationAdminControlador::class, 'operationsHistory']);
    Route::get('/operations/notifications', [RedAviationAdminControlador::class, 'operationsNotifications']);
    Route::put('/reservations/{reservation}/reschedule', [RedAviationAdminControlador::class, 'rescheduleReservation']);
    Route::post('/reservations/{reservation}/cancel', [RedAviationAdminControlador::class, 'cancelReservation']);
    Route::post('/operations/aircraft-blocks', [RedAviationAdminControlador::class, 'createAircraftAvailabilityBlock']);
    Route::post('/operations/aircraft-blocks/{block}/release', [RedAviationAdminControlador::class, 'releaseAircraftAvailabilityBlock']);
    Route::get('/aeronaves/{aircraft}', [AdministradorControlador::class, 'showAeronave']);
    Route::get('/aircraft-documents/{document}/download', [AeronaveControlador::class, 'downloadAdminDocument']);
    Route::get('/aeronaves/documentos/{document}/descargar', [AeronaveControlador::class, 'downloadAdminDocument']);
    Route::post('/aeronaves/{aircraft}/bloquear', [AdministradorControlador::class, 'blockAeronave']);
    Route::post('/aeronaves/{aircraft}/aprobar', [AdministradorControlador::class, 'approveAeronave']);
    Route::post('/aeronaves/{aircraft}/activar', [AdministradorControlador::class, 'activateAeronave']);
    Route::post('/aeronaves/{aircraft}/desactivar', [AdministradorControlador::class, 'deactivateAeronave']);

    Route::get('/solicitudes', [AdministradorControlador::class, 'flightRequests']);
    Route::get('/cotizaciones', [RedAviationAdminControlador::class, 'quotes']);
    Route::get('/reservas', [AdministradorControlador::class, 'reservations']);
    Route::get('/pagos', [AdministradorControlador::class, 'payments']);
    Route::get('/comisiones', [AdministradorControlador::class, 'commissions']);
    Route::post('/comisiones/{commission}/liberar', [AdministradorControlador::class, 'releaseComision']);

    Route::get('/demos', [AdministradorControlador::class, 'demos']);
    Route::get('/suscripciones', [AdministradorControlador::class, 'subscriptions']);
    Route::get('/planes', [AdministradorControlador::class, 'plans']);
    Route::post('/planes', [AdministradorControlador::class, 'storePlan']);
    Route::put('/planes/{plan}', [AdministradorControlador::class, 'updatePlan']);
    Route::get('/flight-membership-plans', [FlightMembershipAdminControlador::class, 'plans']);
    Route::post('/flight-membership-plans', [FlightMembershipAdminControlador::class, 'storePlan']);
    Route::get('/flight-membership-plans/{plan}', [FlightMembershipAdminControlador::class, 'showPlan']);
    Route::put('/flight-membership-plans/{plan}', [FlightMembershipAdminControlador::class, 'updatePlan']);
    Route::patch('/flight-membership-plans/{plan}/status', [FlightMembershipAdminControlador::class, 'updatePlanStatus']);
    Route::get('/flight-memberships', [FlightMembershipAdminControlador::class, 'memberships']);
    Route::get('/flight-memberships/{membership}', [FlightMembershipAdminControlador::class, 'showMembership']);
    Route::post('/flight-memberships/{membership}/adjustment', [FlightMembershipAdminControlador::class, 'adjustment']);

    Route::get('/reportes', [RedAviationAdminControlador::class, 'reports']);
    Route::get('/auditoria', [RedAviationAdminControlador::class, 'auditLogs']);
    Route::get('/configuracion', [RedAviationAdminControlador::class, 'settings']);
    Route::put('/configuracion', [RedAviationAdminControlador::class, 'updateSettings']);
});
