<?php

return [
    'demo_days' => env('SKYGROUP_DEMO_DAYS', 15),
    'default_currency' => env('SKYGROUP_CURRENCY', 'USD'),
    'commission_rate' => env('SKYGROUP_COMMISSION_RATE', 0.10),
    'token_ttl_days' => env('SKYGROUP_TOKEN_TTL_DAYS', 30),
    'dynamic_flight_time_enabled' => (bool) env('DYNAMIC_FLIGHT_TIME_ENABLED', true),
    'flight_time_model' => env('FLIGHT_TIME_MODEL', 'operational'),
    'pricing_debug' => (bool) env('PRICING_DEBUG', false),
    'frontend_pricing_debug' => (bool) env('VITE_PRICING_DEBUG', false),
    'minimum_route_price_v2_enabled' => (bool) env('MINIMUM_ROUTE_PRICE_V2_ENABLED', false),
    'dynamic_flight_time' => [
        'rounding_strategy' => env('FLIGHT_TIME_ROUNDING_STRATEGY', 'ceil'),
        'global_profile' => [
            'taxi_out_minutes' => 4.0,
            'taxi_in_minutes' => 3.0,
            'takeoff_minutes' => 1.0,
            'landing_minutes' => 2.0,
            'climb_minutes' => 12.0,
            'climb_distance_nm' => 40.0,
            'descent_minutes' => 10.0,
            'descent_distance_nm' => 35.0,
            'fixed_operational_minutes' => 3.0,
            'short_leg_threshold_nm' => 180.0,
            'medium_leg_threshold_nm' => 500.0,
            'short_leg_speed_factor' => 0.80,
            'medium_leg_speed_factor' => 0.90,
            'long_leg_speed_factor' => 1.00,
            'rounding_increment_minutes' => 5.0,
        ],
        'profiles_by_aircraft_type' => [
            'Helicoptero' => [
                'climb_minutes' => 7.0,
                'climb_distance_nm' => 10.0,
                'descent_minutes' => 6.0,
                'descent_distance_nm' => 10.0,
                'short_leg_speed_factor' => 0.78,
                'medium_leg_speed_factor' => 0.88,
                'long_leg_speed_factor' => 0.95,
            ],
            'Turboprop' => [
                'climb_minutes' => 10.0,
                'climb_distance_nm' => 20.0,
                'descent_minutes' => 8.0,
                'descent_distance_nm' => 18.0,
                'short_leg_speed_factor' => 0.76,
                'medium_leg_speed_factor' => 0.87,
                'long_leg_speed_factor' => 0.96,
            ],
            'Light Jet' => [
                'climb_minutes' => 12.0,
                'climb_distance_nm' => 35.0,
                'descent_minutes' => 10.0,
                'descent_distance_nm' => 30.0,
                'short_leg_speed_factor' => 0.74,
                'medium_leg_speed_factor' => 0.86,
                'long_leg_speed_factor' => 0.97,
            ],
            'Mid Jet' => [
                'climb_minutes' => 14.0,
                'climb_distance_nm' => 55.0,
                'descent_minutes' => 10.0,
                'descent_distance_nm' => 40.0,
                'short_leg_speed_factor' => 0.76,
                'medium_leg_speed_factor' => 0.88,
                'long_leg_speed_factor' => 1.00,
            ],
            'Heavy Jet' => [
                'climb_minutes' => 16.0,
                'climb_distance_nm' => 70.0,
                'descent_minutes' => 12.0,
                'descent_distance_nm' => 55.0,
                'short_leg_speed_factor' => 0.80,
                'medium_leg_speed_factor' => 0.90,
                'long_leg_speed_factor' => 1.00,
            ],
            'Ultra Long Range' => [
                'climb_minutes' => 18.0,
                'climb_distance_nm' => 85.0,
                'descent_minutes' => 13.0,
                'descent_distance_nm' => 65.0,
                'short_leg_speed_factor' => 0.82,
                'medium_leg_speed_factor' => 0.92,
                'long_leg_speed_factor' => 1.00,
            ],
        ],
    ],
];
